spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://snapshop-auth
          predicates:
            - Path=/api/auth/**
        - id: user
          uri: lb://snapshop-user
          predicates:
            - Path=/api/users/**
        - id: product
          uri: lb://snapshop-product
          predicates:
            - Path=/api/products/**
        - id: seckill
          uri: lb://snapshop-seckill
          predicates:
            - Path=/api/seckill/**
        - id: order
          uri: lb://snapshop-order
          predicates:
            - Path=/api/orders/**
        - id: payment
          uri: lb://snapshop-payment
          predicates:
            - Path=/api/payments/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
